#!/usr/bin/env python

"""
PC-BASIC - GW-BASIC/BASICA/Cartridge BASIC compatible interpreter

(c) 2013--2020 Rob Hagemans
This file is released under the GNU GPL version 3 or later.
"""
import logging

class Boom(object):
    def __getattr__(self, attr):
        logging.error(attr)
        raise ValueError(attr)

    def __setattr__(self, attr, value):
        logging.error(attr)
        raise ValueError(attr)

import sys
#sys.stdin.close() # = Boom()
#sys.stdout.close() # = Boom()
#sys.stderr.close() # = Boom()

from pcbasic import main
main()
